=== italoherbert/explab/explab-2.4.3/conf/ajuda/conteudos.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="arquivo">
        <xs:complexType>
            <xs:attribute name="nome" type="xs:string" use="required" />            
        </xs:complexType>
    </xs:element>

    <xs:element name="propriedade">
        <xs:complexType>
            <xs:attribute name="nome" type="xs:string" use="required" />            
        </xs:complexType>
    </xs:element>

    <xs:element name="chave">
        <xs:complexType>
            <xs:attribute name="nome" type="xs:string" use="required" />
            <xs:attribute name="peso" type="xs:nonNegativeInteger" use="required" />            
        </xs:complexType>
    </xs:element>        

    <xs:element name="conteudo" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="optional" />
            <xs:all>
                <xs:element ref="chave" minOccurs="0" maxOccurs="unbounded" /> 
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="pagina" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
            <xs:attribute name="url" type="xs:string" use="required" />            
            <xs:all>
                <xs:element ref="conteudo" minOccurs="0" maxOccurs="unbounded" /> 
                <xs:element ref="chave" minOccurs="0" maxOccurs="unbounded" />
            </xs:all>
        </xs:complexType>
    </xs:element>
        
    <xs:element name="conteudos" minOccurs="1" maxOccurs="1">
        <xs:complexType>
            <xs:all>
                <xs:element ref="propriedade" minOccurs="0" maxOcurrs="unbounded" />
                <xs:element ref="arquivo" minOccurs="0" maxOccurs="unbounded" /> 
                <xs:element ref="pagina" minOccurs="0" maxOccurs="unbounded" /> 
            </xs:all>
        </xs:complexType>
    </xs:element>
            
</xs:schema>

=== italoherbert/explab/explab-2.4.3/conf/ajuda/vars-nativas.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/vars-nativas.html">            
        <chave nome="pi" peso="10" />
        <chave nome="e" peso="10" />
        <chave nome="inf" peso="10" />
        <chave nome="nan" peso="10" />
        <conteudo id="div-por-zero">
            <chave nome="div_por_zero" peso="10" />
            <chave nome="div-por-zero" peso="10" />
        </conteudo>
        <chave nome="usuariodir" peso="10" />
        <chave nome="scriptdir" peso="10" />        
    </pagina>
    
</conteudos>

=== italoherbert/explab/target/classes/ajuda/orientacao-a-objetos.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/orientacao-a-objetos.html">
        <conteudo>
            <chave nome="orientação" peso="13" />
            <chave nome="objetos" peso="15" />
            <chave nome="objeto" peso="15" />
            <chave nome="instancia" peso="15" />
            <chave nome="polimorfismo" peso="15" />
            <chave nome="composição" peso="15" />
            <chave nome="classe" peso="15" />
            <chave nome="classes" peso="15" />
            <chave nome="atributos" peso="12" />            
            <chave nome="construtores" peso="12" />
            <chave nome="construtor" peso="12" />
            <chave nome="funções" peso="12" />
            <chave nome="func" peso="12" />                                    
            <chave nome="subclasses" peso="12" />                
            <chave nome="novo" peso="12" />
            <chave nome="new" peso="12" />        
        </conteudo>
        
        <conteudo id="construtores">
            <chave nome="construtores" peso="15" />
            <chave nome="construtor" peso="15" />    
        </conteudo>
        
        <conteudo id="este">
            <chave nome="este" peso="15" />
            <chave nome="this" peso="15" />
            <chave nome="base" peso="15" />
            <chave nome="func" peso="5" />
            <chave nome="construtor" peso="5" />
            <chave nome="atributo" peso="5" />
            <chave nome="classe" peso="8" />          
        </conteudo>
		
        <conteudo id="super">
            <chave nome="super" peso="15" />
            <chave nome="base" peso="15" />
            <chave nome="func" peso="5" />
            <chave nome="construtor" peso="5" />
            <chave nome="atributo" peso="5" />
            <chave nome="classe" peso="8" />          
        </conteudo>
		
		<conteudo id="extende">
            <chave nome="extende" peso="15" />
            <chave nome="super" peso="10" />
            <chave nome="this" peso="5" />
            <chave nome="construtor" peso="5" />
            <chave nome="atributo" peso="5" />
            <chave nome="classe" peso="10" />          
        </conteudo>		
        
        <conteudo id="subclasses">
            <chave nome="subclasses" peso="15" />
            <chave nome="subclasse" peso="15" />
            <chave nome="classe" peso="12" />      
        </conteudo>
        
        <conteudo id="pacotes">
            <chave nome="pacotes" peso="15" />
            <chave nome="pacote" peso="15" />
            <chave nome="classe" peso="12" />      
        </conteudo>
        
        <conteudo id="classes-nomes-iguais">
            <chave nome="instancia" peso="8" />
            <chave nome="novo" peso="8" />
            <chave nome="new" peso="8" />
            <chave nome="pacotes" peso="10" />
            <chave nome="pacote" peso="10" />
            <chave nome="classe" peso="8" />      
        </conteudo>
        
        <conteudo id="extende">
            <chave nome="extende" peso="15" />
            <chave nome="herança" peso="15" />
            <chave nome="new" peso="8" />
            <chave nome="pacotes" peso="10" />
            <chave nome="pacote" peso="10" />
            <chave nome="classe" peso="8" />      
        </conteudo>
    </pagina>
</conteudos>

=== italoherbert/explab/conf/ajuda/tratamento-de-excecoes.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/tratamento-de-excecoes.html">   
        <conteudo>
            <chave nome="lance" peso="15" />
            <chave nome="tratar" peso="15" />           
            <chave nome="excecoes-personalizadas" peso="10" />
            <chave nome="finalize" peso="15" />
            <chave nome="lista-de-erros" peso="15" />            
            <chave nome="exception" peso="8" />
            <chave nome="exceptions" peso="8" />
        </conteudo>        
        <conteudo id="tratar">
            <chave nome="tratar" peso="10" />           
            <chave nome="throws" peso="6" />
            <chave nome="exception" peso="3" />
            <chave nome="exceptions" peso="3" />      
        </conteudo> 
        <conteudo id="lance">
            <chave nome="lance" peso="15" />           
            <chave nome="throw" peso="10" />
            <chave nome="tratar" peso="6" />            
        </conteudo> 
        <conteudo id="excecoes-personalizadas">
            <chave nome="exceções" peso="10" />           
            <chave nome="personalizadas" peso="6" />
            <chave nome="exception" peso="6" />
            <chave nome="exceptions" peso="6" />
        </conteudo>
        <conteudo id="lista-de-erros">
            <chave nome="pilha" peso="12" />           
            <chave nome="fila" peso="12" />
            <chave nome="erros" peso="10" />
            <chave nome="printStackTrace" peso="15" />
            <chave nome="imprime" peso="3" />            
        </conteudo>                         
    </pagina>    
    
</conteudos>

=== italoherbert/explab/src/main/test/target/classes/ajuda/estruturas-de-decisao.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/estruturas-de-decisao.html">
        <conteudo>
            <chave nome="estrutura" peso="8" />
            <chave nome="decisão" peso="10" />
            <chave nome="condição" peso="10" />
            <chave nome="fluxo" peso="8" />
            <chave nome="execução" peso="8" />
            <chave nome="bloco" peso="5" />
            <chave nome="codigo" peso="5" />
        </conteudo>
        <conteudo id="se">
            <chave nome="se" peso="10" />
            <chave nome="entao" peso="10" />
            <chave nome="senao" peso="10" />
            <chave nome="if" peso="10" />
            <chave nome="then" peso="10" />
            <chave nome="else" peso="10" />
        </conteudo>
        <conteudo id="compare/caso">
            <chave nome="compare" peso="10" />
            <chave nome="caso" peso="10" />
            <chave nome="padrao" peso="10" />
            <chave nome="pare" peso="8" />            
            <chave nome="switch" peso="15" />
            <chave nome="case" peso="10" />
            <chave nome="default" peso="10" /> 
            <chave nome="break" peso="8" />          
        </conteudo>
    </pagina>
    
</conteudos>

=== italoherbert/explab/explab-2.4.3/conf/ajuda/conteudos.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
    
    <propriedade nome="conf.basedir">conf</propriedade>
    <propriedade nome="conf.ajuda">${conf.basedir}/ajuda</propriedade>
    <propriedade nome="conf.ajuda.classes">${conf.ajuda}/classes</propriedade>

    <propriedade nome="doc.url">https://www.italoinfo.com.br/projetos/explab/doc</propriedade>
    <propriedade nome="doc.paginas">paginas</propriedade>      
    <propriedade nome="doc.paginas.classes">${doc.paginas}/classes</propriedade>

    <arquivo>${conf.ajuda}/comandos.xml</arquivo>    
    <arquivo>${conf.ajuda}/funcs-nativas.xml</arquivo>
    <arquivo>${conf.ajuda}/vars-nativas.xml</arquivo>
    <arquivo>${conf.ajuda}/tipos-de-dados.xml</arquivo>
    <arquivo>${conf.ajuda}/expressoes.xml</arquivo>
    <arquivo>${conf.ajuda}/incrementos-e-decrementos.xml</arquivo>
    <arquivo>${conf.ajuda}/estruturas-de-decisao.xml</arquivo>
    <arquivo>${conf.ajuda}/estruturas-de-repeticao.xml</arquivo>
    <arquivo>${conf.ajuda}/vetores-e-matrizes.xml</arquivo>
    <arquivo>${conf.ajuda}/funcoes.xml</arquivo>
    <arquivo>${conf.ajuda}/orientacao-a-objetos.xml</arquivo>
    <arquivo>${conf.ajuda}/graficos-e-plotagem.xml</arquivo>
    <arquivo>${conf.ajuda.classes}/classes-nativas.xml</arquivo>
    
</conteudos>

=== italoherbert/explab/src/main/test/target/classes/ajuda/funcoes.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/funcoes.html">            
        <conteudo>
            <chave nome="func" peso="15" />
            <chave nome="function" peso="15" />                        
            <chave nome="função" peso="15" />            
            <chave nome="funções" peso="15" />
            <chave nome="parametros" peso="8" />
            <chave nome="retorne" peso="12" />
            <chave nome="return" peso="12" />
            <chave nome="recursividade" peso="10" />
            <chave nome="variáveis" peso="5" />
            <chave nome="subprogramas" peso="10" />
            <chave nome="bloco" peso="5" />
            <chave nome="codigo" peso="5" />
        </conteudo>
        
        <conteudo id="recursividade" >
            <chave nome="recursividade" peso="15" />
            <chave nome="recursiva" peso="15" />            
            <chave nome="recursivo" peso="15" />
            <chave nome="func" peso="10" />
            <chave nome="function" peso="10" />                        
            <chave nome="função" peso="10" />            
            <chave nome="funções" peso="10" />
            <chave nome="retorne" peso="8" />
            <chave nome="retorne" peso="8" />            
            <chave nome="parametros" peso="8" />
            <chave nome="subprogramas" peso="10" />
        </conteudo>
               
        <conteudo id="func-var" >
            <chave nome="var" peso="12" />
            <chave nome="variavel" peso="12" />
            <chave nome="func" peso="12" />
            <chave nome="function" peso="12" />                        
            <chave nome="função" peso="12" />            
            <chave nome="funções" peso="12" />
            <chave nome="retorne" peso="8" />
            <chave nome="retorne" peso="8" />            
            <chave nome="parametros" peso="8" />
            <chave nome="subprogramas" peso="10" />
        </conteudo>
    </pagina>
        
</conteudos>

=== italoherbert/explab/src/main/test/target/classes/ajuda/incrementos-e-decrementos.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/incrementos-e-decrementos.html">
        <conteudo>
            <chave nome="incremento" peso="15" />
            <chave nome="decremento" peso="15" />
            <chave nome="incrementos" peso="15" />
            <chave nome="decrementos" peso="15" />
            <chave nome="++" peso="15" />
            <chave nome="--" peso="15" />
            <chave nome="+=" peso="15" />
            <chave nome="-=" peso="15" />
            <chave nome="mais" peso="10" />
            <chave nome="menos" peso="10" />
            <chave nome="igual" peso="5" />
        </conteudo>
    </pagina>
    
</conteudos>

=== italoherbert/explab/explab-2.4/conf/ajuda/graficos-e-plotagem.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/graficos-e-plotagem.html">
        <conteudo>
            <chave nome="plot" peso="12" />
            <chave nome="plot3d" peso="12" />
            <chave nome="PC2D" peso="10" />
            <chave nome="PC3D" peso="10" />
            <chave nome="Func2D" peso="10" />
            <chave nome="Func3D" peso="10" />
            <chave nome="Dados2D" peso="10" />
            <chave nome="Dados3D" peso="10" />
            <chave nome="Superficie3D" peso="10" />
        </conteudo>
        <conteudo id="plotagem2d">
            <chave nome="plot" peso="14" />
            <chave nome="PC2D" peso="12" />
            <chave nome="Func2D" peso="12" />
            <chave nome="Dados2D" peso="12" />
        </conteudo>
        <conteudo id="plotagem3d">
            <chave nome="plot" peso="14" />
            <chave nome="PC3D" peso="12" />
            <chave nome="Func3D" peso="12" />
            <chave nome="Dados3D" peso="12" />
            <chave nome="Superficie3D" peso="12" />
        </conteudo>
    </pagina>
</conteudos>
