=== italoherbert/explab/explab-2.4.3/conf/ajuda/conteudos.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="arquivo">
        <xs:complexType>
            <xs:attribute name="nome" type="xs:string" use="required" />            
        </xs:complexType>
    </xs:element>

    <xs:element name="propriedade">
        <xs:complexType>
            <xs:attribute name="nome" type="xs:string" use="required" />            
        </xs:complexType>
    </xs:element>

    <xs:element name="chave">
        <xs:complexType>
            <xs:attribute name="nome" type="xs:string" use="required" />
            <xs:attribute name="peso" type="xs:nonNegativeInteger" use="required" />            
        </xs:complexType>
    </xs:element>        

    <xs:element name="conteudo" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="optional" />
            <xs:all>
                <xs:element ref="chave" minOccurs="0" maxOccurs="unbounded" /> 
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="pagina" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
            <xs:attribute name="url" type="xs:string" use="required" />            
            <xs:all>
                <xs:element ref="conteudo" minOccurs="0" maxOccurs="unbounded" /> 
                <xs:element ref="chave" minOccurs="0" maxOccurs="unbounded" />
            </xs:all>
        </xs:complexType>
    </xs:element>
        
    <xs:element name="conteudos" minOccurs="1" maxOccurs="1">
        <xs:complexType>
            <xs:all>
                <xs:element ref="propriedade" minOccurs="0" maxOcurrs="unbounded" />
                <xs:element ref="arquivo" minOccurs="0" maxOccurs="unbounded" /> 
                <xs:element ref="pagina" minOccurs="0" maxOccurs="unbounded" /> 
            </xs:all>
        </xs:complexType>
    </xs:element>
            
</xs:schema>

=== italoherbert/explab/src/main/test/target/classes/ajuda/estruturas-de-repeticao.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/estruturas-de-repeticao.html">
        <conteudo id="enquanto">
            <chave nome="repetição" peso="10" />
            <chave nome="loop" peso="10" />
            <chave nome="bloco" peso="5" />
            <chave nome="codigo" peso="5" />
        </conteudo>
        <conteudo id="enquanto">
            <chave nome="enquanto" peso="10" />
            <chave nome="faça" peso="8" />                        
        </conteudo>
        <conteudo id="para">
            <chave nome="para" peso="10" />
            <chave nome="faça" peso="8" />   
        </conteudo>
        <conteudo id="faca/enquanto">
            <chave nome="faca/enquanto" peso="10" />
            <chave nome="faça" peso="8" />    
        </conteudo>
    </pagina>
    
</conteudos>

=== italoherbert/explab/src/main/test/target/classes/ajuda/tipos-de-dados.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/tipos-de-dados.html">   
        <conteudo id="real">
            <chave nome="tipo" peso="10" />           
            <chave nome="real" peso="10" />
            <chave nome="numero" peso="8" />
            <chave nome="integer" peso="4" />            
            <chave nome="flutuante" peso="4" />            
            <chave nome="numerica" peso="4" />
            <chave nome="numerico" peso="4" />
        </conteudo>
        <conteudo id="matriz">
            <chave nome="tipo" peso="10" />           
            <chave nome="matriz" peso="6" />
            <chave nome="vetor" peso="6" />
            <chave nome="vetores" peso="6" />
            <chave nome="unidimensional" peso="4" />
            <chave nome="bidimensional" peso="4" />            
        </conteudo> 
        <conteudo id="string">
            <chave nome="tipo" peso="10" />           
            <chave nome="string" peso="6" />
            <chave nome="caracter" peso="6" />
            <chave nome="caracteres" peso="6" />
            <chave nome="texto" peso="6" />           
        </conteudo>
        <conteudo id="boolean">
            <chave nome="tipo" peso="10" />           
            <chave nome="boolean" peso="6" />
            <chave nome="booleano" peso="6" />
            <chave nome="verdade" peso="3" />
            <chave nome="falso" peso="3" />
            <chave nome="true" peso="2" />            
            <chave nome="false" peso="2" />            
        </conteudo> 
        <conteudo id="objeto">
            <chave nome="tipo" peso="10" />           
            <chave nome="objeto" peso="6" />
            <chave nome="instancia" peso="6" />
            <chave nome="atributo" peso="3" />
            <chave nome="func" peso="3" />
            <chave nome="construtor" peso="6" />            
            <chave nome="classe" peso="5" />            
            <chave nome="subclasse" peso="5" />            
        </conteudo> 
        <conteudo id="func">
            <chave nome="tipo" peso="10" />           
            <chave nome="func" peso="6" />
            <chave nome="variavel" peso="6" />
        </conteudo>                
    </pagina>    
    
</conteudos>

=== italoherbert/explab/src/main/test/target/classes/ajuda/funcs-nativas.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/funcs-nativas.html">            
        <chave nome="abs" peso="10" />
        <chave nome="acos" peso="10" />
        <conteudo id="asen">
            <chave nome="asen" peso="10" />
            <chave nome="asin" peso="10" />
        </conteudo> 
        <chave nome="arredonda" peso="10" />
        <chave nome="atan" peso="10" />
        <chave nome="atan2" peso="10" />
        <chave nome="caractere" peso="10" />
        <chave nome="cos" peso="10" />        
        <chave nome="div" peso="10" />           
        <chave nome="exp" peso="10" />   
        <chave nome="fexec" peso="10" />       
        <chave nome="fracionario" peso="10" /> 
        <chave nome="getcharset" peso="10" />      
        <chave nome="graus" peso="10" />       
        <chave nome="inteiro" peso="10" />       
        <chave nome="log" peso="10" />       
        <chave nome="log10" peso="10" />       
        <chave nome="logN" peso="10" />       
        <chave nome="maiusculas" peso="10" />       
        <chave nome="minusculas" peso="10" />       
        <chave nome="matmult" peso="10" />       
        <chave nome="mod" peso="10" />               
        <chave nome="mult" peso="10" />              
        <conteudo id="parastr">
            <chave nome="parastr" peso="10" />
            <chave nome="valueof" peso="10" />
            <chave nome="parsestring" peso="10" />
            <chave nome="parsestr" peso="10" />
            <chave nome="converte" peso="2" />
            <chave nome="converter" peso="2" />
        </conteudo> 
        <chave nome="plot" peso="10" />              
        <conteudo id="plot3d">
            <chave nome="plot3d" peso="10" />
            <chave nome="surf" peso="10" />
            <chave nome="mesh" peso="10" />            
            <chave nome="plot3" peso="10" />
        </conteudo> 
        <conteudo id="pot">
            <chave nome="pot" peso="10" />
            <chave nome="pow" peso="10" />
        </conteudo>                     
        <chave nome="radianos" peso="10" />              
        <chave nome="random" peso="10" />              
        <conteudo id="rquad">
            <chave nome="rquad" peso="10" />
            <chave nome="sqrt" peso="10" />
        </conteudo> 
        <conteudo id="sen">
            <chave nome="sen" peso="10" />
            <chave nome="sin" peso="10" />
        </conteudo>              
        <chave nome="setcharset" peso="10" />      
        <chave nome="soma" peso="10" />
        <conteudo id="strtam">
            <chave nome="strtam" peso="10" />           
            <chave nome="strlen" peso="10" />           
            <chave nome="length" peso="10" />           
        </conteudo>                               
        <conteudo id="strparareal">
            <chave nome="strparareal" peso="10" />           
            <chave nome="parseint" peso="10" />           
            <chave nome="parsedouble" peso="10" />           
            <chave nome="parsefloat" peso="10" />           
            <chave nome="converter" peso="4" />             
            <chave nome="converte" peso="4" />                       
        </conteudo>  
        <conteudo id="strparabool">
            <chave nome="strparabool" peso="10" />           
            <chave nome="parsebool" peso="10" />           
            <chave nome="parseboolean" peso="10" />          
            <chave nome="converter" peso="3" />             
            <chave nome="converte" peso="3" />               
        </conteudo> 
        
        <chave nome="sub" peso="10" />                   
        <chave nome="substring" peso="10" />           
        <chave nome="tan" peso="10" />           
        <conteudo id="tipode">
            <chave nome="tipode" peso="10" />
            <chave nome="sizeof" peso="10" />
        </conteudo>           
        <chave nome="transposta" peso="10" />           
        <conteudo id="vetesp">           
            <chave nome="vetesp" peso="10" />
            <chave nome="linspace" peso="10" />
        </conteudo>
        <conteudo id="xmalhagrade">           
            <chave nome="xmalhagrade" peso="10" />
            <chave nome="meshgrid" peso="10" />
        </conteudo>
        <conteudo id="ymalhagrade">           
            <chave nome="ymalhagrade" peso="10" />
            <chave nome="meshgrid" peso="10" />
        </conteudo>
    </pagina>
        
</conteudos>

=== italoherbert/explab/explab-2.4.3/conf/ajuda/classes/g2d-classes-nativas.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">        

    <propriedade nome="conf.ajuda.classes.plot2d">${conf.ajuda.classes}/plot2d</propriedade>
    <propriedade nome="doc.paginas.classes.plot2d">${doc.paginas.classes}/plot2d</propriedade>
        
    <pagina url="${doc.paginas.classes.plot2d}/PC2D.html"> 
        <conteudo>
            <chave nome="grafico" peso="7" />
            <chave nome="graficos" peso="7" />
            <chave nome="plot" peso="10" />
            <chave nome="classe" peso="6" />                     
            <chave nome="plano" peso="5" />                        
            <chave nome="cartesiano" peso="4" />  
            <chave nome="função" peso="5" />                 
            <chave nome="function" peso="5" />                      
            <chave nome="2d" peso="8" />
            <chave nome="PC2D" peso="10" />                        
        </conteudo>
    </pagina>
    
    <pagina url="${doc.paginas.classes.plot2d}/Func2D.html"> 
        <conteudo>  
            <chave nome="função" peso="9" />                 
            <chave nome="function" peso="9" />                     
            <chave nome="Func2D" peso="10" />                        
        </conteudo>
    </pagina>
    
    <pagina url="${doc.paginas.classes.plot2d}/Dados2D.html"> 
        <conteudo>
            <chave nome="dados" peso="7" />
            <chave nome="Dados2D" peso="10" />                        
        </conteudo>
    </pagina>
    
</conteudos>

=== italoherbert/explab/src/main/test/target/classes/ajuda/comandos.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/comandos.html">       
        <chave nome="script" peso="10" />      
        <conteudo id="use">
            <chave nome="use" peso="10" />      
            <chave nome="importe" peso="10" />
            <chave nome="import" peso="10" />
            <chave nome="include" peso="10" />
        </conteudo>
        <chave nome="cd" peso="10" />      
        <conteudo id="ls">
            <chave nome="ls" peso="10" />      
            <chave nome="dir" peso="10" />
        </conteudo>     
        <chave nome="liste" peso="10" />      
        <chave nome="ajuda" peso="10" /> 
        <conteudo id="sair">
            <chave nome="sair" peso="10" />      
            <chave nome="exit" peso="10" />
            <chave nome="quit" peso="10" />
        </conteudo>  
        <conteudo id="exiba">
            <chave nome="exiba" peso="10" />      
            <chave nome="print" peso="10" />
            <chave nome="printf" peso="10" />      
            <chave nome="cout" peso="10" />
            <chave nome="write" peso="10" />
        </conteudo>   
        <conteudo id="exibaln">
            <chave nome="exibaln" peso="10" />      
            <chave nome="print" peso="8" />
            <chave nome="printf" peso="8" />      
            <chave nome="cout" peso="8" />
            <chave nome="writeln" peso="10" />
        </conteudo> 
        <conteudo id="leialn">
            <chave nome="leialn" peso="10" />      
            <chave nome="read" peso="10" />
            <chave nome="scanf" peso="10" />      
            <chave nome="readln" peso="10" />
            <chave nome="cin" peso="10" />
        </conteudo>      
        <chave nome="continue" peso="10" />
        <conteudo id="pare">
            <chave nome="pare" peso="10" />      
            <chave nome="break" peso="10" />
        </conteudo> 
    </pagina>
    
</conteudos>

=== italoherbert/explab/conf/ajuda/expressoes.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/expressoes-aritmeticas.html">   
        <conteudo>
            <chave nome="aritmeticas" peso="10" />
            <chave nome="aritmetica" peso="10" />
            <chave nome="expressões" peso="10" />
            <chave nome="expressão" peso="10" />
            <chave nome="expressao" peso="10" />
            <chave nome="expressoes" peso="10" />
            <chave nome="operadores" peso="8" />
            <chave nome="soma" peso="5" />
            <chave nome="subtração" peso="5" />
            <chave nome="multiplicação" peso="5" />
            <chave nome="divisão" peso="5" />
            <chave nome="resto" peso="5" />
            <chave nome="potência" peso="5" />
            <chave nome="+" peso="5" />
            <chave nome="-" peso="10" />
            <chave nome="*" peso="10" />
            <chave nome="/" peso="10" />
            <chave nome="^" peso="10" />
            <chave nome="%" peso="10" />
            <chave nome="+=" peso="10" />
            <chave nome="-=" peso="10" />
            <chave nome="*=" peso="10" />
            <chave nome="/=" peso="10" />
            <chave nome="%=" peso="10" />
            <chave nome=".+" peso="5" />
            <chave nome=".-" peso="10" />
            <chave nome=".*" peso="10" />
            <chave nome="./" peso="10" />
            <chave nome=".^" peso="10" />
        </conteudo>
    </pagina>
    
    <pagina url="${doc.paginas}/expressoes-booleanas.html">   
        <conteudo>
            <chave nome="booleana" peso="10" />
            <chave nome="booleanas" peso="10" />
            <chave nome="expressões" peso="10" />
            <chave nome="expressão" peso="10" />
            <chave nome="operadores" peso="7" />
            <chave nome="&amp;" peso="10" />
            <chave nome="|" peso="10" />
            <chave nome="#" peso="10" />
            <chave nome="!" peso="10" />
            <chave nome="ou" peso="10" />
            <chave nome="não" peso="10" />
            <chave nome="nao" peso="10" />
            <chave nome="exclusivo" peso="10" />
            <chave nome="and" peso="10" />
            <chave nome="or" peso="10" />
            <chave nome="not" peso="10" />
            <chave nome="xor" peso="10" />
        </conteudo>
    </pagina>
    
</conteudos>

=== italoherbert/explab/conf/ajuda/classes/classes-nativas.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <arquivo>${conf.ajuda.classes}/g2d-classes-nativas.xml</arquivo>
    <arquivo>${conf.ajuda.classes}/g3d-classes-nativas.xml</arquivo>
    
    <pagina url="${doc.paginas.classes}/RGB.html"> 
        <conteudo>
            <chave nome="classe" peso="6" />                       
            <chave nome="cor" peso="8" />                       
            <chave nome="cores" peso="8" />                       
            <chave nome="color" peso="8" />                      
            <chave nome="RGB" peso="10" />                        
        </conteudo>
    </pagina>
    
    <pagina url="${doc.paginas.classes}/JanelaConfig.html"> 
        <conteudo>            
            <chave nome="JanelaConfig" peso="10" />                        
            <chave nome="Janela" peso="8" />                        
            <chave nome="Config" peso="4" />
            <chave nome="classe" peso="6" />
        </conteudo>
    </pagina>
    
    <pagina url="${doc.paginas.classes}/GradeConfig.html"> 
        <conteudo>
            <chave nome="GradeConfig" peso="10" />                        
            <chave nome="Grade" peso="8" />                        
            <chave nome="Config" peso="4" />                        
            <chave nome="classe" peso="6" />
        </conteudo>
    </pagina>
    
    <pagina url="${doc.paginas.classes}/PontoConfig.html"> 
        <conteudo>
            <chave nome="PontoConfig" peso="10" />                        
            <chave nome="Ponto" peso="8" />                        
            <chave nome="Config" peso="4" />                        
            <chave nome="classe" peso="6" />
        </conteudo>
    </pagina>
    
    <pagina url="${doc.paginas.classes}/LinhaConfig.html"> 
        <conteudo>
            <chave nome="LinhaConfig" peso="10" />                        
            <chave nome="Linha" peso="8" />                        
            <chave nome="Config" peso="4" />                        
            <chave nome="classe" peso="6" />
        </conteudo>
    </pagina>
    
    <pagina url="${doc.paginas.classes}/PoligonoConfig.html"> 
        <conteudo>
            <chave nome="PoligonoConfig" peso="10" />                        
            <chave nome="Poligono" peso="8" />                        
            <chave nome="Config" peso="4" />                        
            <chave nome="classe" peso="6" />
        </conteudo>
    </pagina>
    
</conteudos>

=== italoherbert/explab/conf/ajuda/vetores-e-matrizes.xml
<?xml version="1.0" encoding="UTF-8"?>

<conteudos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="conteudos.xsd">
        
    <pagina url="${doc.paginas}/vetores-e-matrizes.html">   
        <conteudo id="arrays">
            <chave nome="arrays" peso="20" />
            <chave nome="vetores" peso="10" />            
            <chave nome="vetor" peso="10" />            
            <chave nome="lista" peso="10" />            
            <chave nome="listas" peso="10" />            
            <chave nome="unidimensional" peso="10" />
        </conteudo>
        <conteudo id="matrizes">
            <chave nome="bidimensional" peso="20" />
            <chave nome="matrizes" peso="10" />                        
            <chave nome="matriz" peso="10" />
            <chave nome="arrays" peso="7" />
            <chave nome="vetores" peso="9" />            
            <chave nome="lista" peso="3" />            
            <chave nome="listas" peso="3" />            
        </conteudo>
        <conteudo id="submatrizes">
            <chave nome="submatrizes" peso="20" />                        
            <chave nome="matrizes" peso="10" />                        
            <chave nome="matriz" peso="10" />
            <chave nome="arrays" peso="7" />
            <chave nome="vetores" peso="9" />            
            <chave nome="lista" peso="3" />            
            <chave nome="listas" peso="3" />            
            <chave nome="bidimensional" peso="4" />
            <chave nome="unidimensional" peso="4" />
        </conteudo>
    </pagina>

</conteudos>
