=== italoherbert/explab/explab-2.4.3/conf/exceptions.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="exception">
        <xs:complexType>
            <xs:attribute name="classeNome" type="xs:string" use="required" />
            <xs:all>
                <xs:element name="chave" minOccurs="1" maxOccurs="unbounded" /> 
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="exceptions" minOccurs="1" maxOccurs="1">
        <xs:complexType>
            <xs:all>
                <xs:element ref="exception" minOccurs="0" maxOccurs="unbounded" /> 
                <xs:element name="pacote" minOccurs="1" maxOccurs="1" /> 
                <xs:element name="exception-classe-nome" minOccurs="1" maxOccurs="1" /> 
                <xs:element name="runtime-exception-classe-nome" minOccurs="1" maxOccurs="1" /> 
            </xs:all>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== italoherbert/explab/conf/exceptions.xml
<?xml version="1.0" encoding="UTF-8"?>

<exceptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="exceptions.xsd">
        
    <pacote>explab.ex</pacote>
    
    <exception-classe-nome>Exception</exception-classe-nome>
    <runtime-exception-classe-nome>RuntimeException</runtime-exception-classe-nome>    
    
    <exeption classeNome="TermoOuCHEsperadoException">
        <chave>abre.chaves.esperado</chave>
        <chave>fecha.chaves.esperado</chave>
        <chave>abre.colchetes.esperado</chave>
        <chave>fecha.colchetes.esperado</chave>
        <chave>abre.parenteses.esperado</chave>
        <chave>fecha.parenteses.esperado</chave>

        <chave>aspas.duplas.esperadas</chave>
        <chave>apostrofo.esperado</chave>
        <chave>virgula.ou.ponto.e.virgula.esperado</chave>
        <chave>ponto.ou.ponto.e.virgula.esperado</chave>
        <chave>virgula.ou.fecha.parenteses.esperado</chave>
        <chave>ponto.e.virgula.esperado</chave>
        <chave>ponto.esperado</chave>
        <chave>dois.pontos.esperado</chave>
        <chave>cifrao.esperado</chave>
        <chave>algarismo.numerico.esperado</chave>
        <chave>espaco.esperado</chave>
        <chave>num.op.experado</chave>        
        
        <chave>operando.booleano.esperado</chave>
        <chave>operando.numerico.esperado</chave>
        <chave>operador.comp.esperado</chave>
    </exeption>
    
    <exception classeNome="TermoNaoExperadoException">        
        <chave>fecha.parenteses.inesperado</chave>
        <chave>ponto.inesperado</chave>
        <chave>palavra.reservada.inesperada</chave>
    </exception>
    
    <exception classeNome="PalavraReservadaException">        
        <chave>existe.como.palavra.reservada</chave>
        <chave>palavra.reservada.esperada</chave>
        <chave>palavras.reservadas.esperadas</chave>
    </exception>
    
    <exception classeNome="VarReservadaException">        
        <chave>existe.como.var.reservada</chave>
        <chave>tentativa.alterar.var.reservada</chave>
    </exception>
        
    <exception classeNome="ValorRealEsperadoException">
        <chave>oper.tipo.real.esperado</chave>
        <chave>var.tipo.real.esperado</chave>
        <chave>valor.real.esperado</chave>
  </exception>
    
    <exception classeNome="ValorBooleanoEsperadoException">
        <chave>valor.booleano.esperado</chave>
        <chave>param.tipo.boolean.esperado</chave>
    </exception>
    
    <exception classeNome="ValorBooleanoEsperadoException">
        <chave>valor.booleano.esperado</chave>
    </exception>
    
    <exception classeNome="ValorStringEsperadoException">
        <chave>valor.string.esperado</chave>
        <chave>param.tipo.string.esperado</chave>
    </exception>
    
    <exception classeNome="ValorObjetoEsperadoException">
        <chave>valor.objeto.esperado</chave>
    </exception>
    
    <exception classeNome="ValorNaoNuloEsperadoException">
        <chave>valor.nao.nulo.esperado</chave>
    </exception>
    
    <exception classeNome="ValorMatrizEsperadoException">
        <chave>param.tipo.matriz.esperado</chave>        
    </exception>
        
    <exception classeNome="ValorMatrizRealEsperadoException">
        <chave>param.tipo.matriz.real.esperado</chave>
        <chave>param.tipo.real.esperado</chave>
    </exception>
    
    <exception classeNome="ValorNumericoEsperadoException.exp">
        <chave>param.numerico.esperado</chave>
    </exception>
    
    <exception classeNome="ObjetoExperadoException.exp">
        <chave>var.tipo.objeto.esperado</chave>        
    </exception>
    
    <exception classeNome="ValorException">
        <chave>valor.esperado</chave>
        <chave>valor.invalido</chave>
    </exception>
    
    <exception classeNome="IncDecException">        
        <chave>inc.var.nao.real</chave>
        <chave>inc.ou.atrib.inst.esperada</chave>
    </exception>
    
    <exception classeNome="VarException">
        <chave>var.invalida</chave>
        <chave>var.tipo.invalido</chave>
        <chave>var.tipos.incompativeis</chave>
        <chave>var.tentativa.de.alterar.constante</chave>
        <chave>var.esperada</chave>
        <chave>var.nao.alterada</chave>
        <chave>var.nao.nomeada</chave>
        <chave>var.nao.lida</chave>
    </exception>
            
    <exception classeNome="ClasseException">
        <chave>classe.instancia.esperada</chave>
        <chave>classe.instancia.de.uma.esperada</chave>
        <chave>classe.esperada</chave>
        <chave>classe.nao.encontrada</chave>
        <chave>classe.obj.chamada.construtor.erro</chave>
        <chave>classe.obj.sem.heranca</chave>
        <chave>classe.def.atrib.invalida</chave>
        <chave>classe.de.excecao.nome.esperado</chave>
        <chave>classe.de.excecao.esperada</chave>
    </exception>
    
    <exception classeNome="ForaDeFuncaoLancamentoException">
        <chave>lancamento.de.excecao.fora.de.funcao</chave>
    </exception>
        
    <exception classeNome="NumExpException">
        <chave>numexp.termo.ou.ch.invalido</chave>
    </exception>
    
    <exception classeNome="BooleanExpException">
        <chave>boolexp.esperada</chave>
        <chave>boolexp.operandos.tipo.real.esperados</chave>
        <chave>boolexp.operador.de.negacao.esperado</chave>
        <chave>boolexp.operador.de.negacao.inesperado</chave>
    </exception>
    
    <exception classeNome="ParamException">
        <chave>param.def.invalida</chave>
        <chave>params.quant.invalida</chave>
        <chave>params.quant.menor.que.esperado</chave>
        <chave>params.tipos.incompativeis</chave>
        <chave>param.nulo</chave>
        <chave>param.maior.que.zero.esperado</chave>
        <chave>param.n1.menor.ou.igual.a.n2.esperado</chave>
        <chave>param.def.esperada</chave>       
    </exception>
    
    <exception classeNome="FuncException">
        <chave>func.void</chave>
        <chave>func.nao.encontrada</chave>
        <chave>func.ou.oper.nao.encontrado</chave>
        <chave>func.retorno.numerico.esperado</chave>
        <chave>func.nome.esperado</chave>
        <chave>func.tratamento.excecao.esperado</chave>
    </exception>
    
    <exception classeNome="ConstrutorException">
        <chave>construtor.ja.existe</chave>
        <chave>construtor.vazio.nao.declarado</chave>
        <chave>construtor.nao.encontrado</chave>
    </exception>
    
    <exception classeNome="MatrizException">
        <chave>matriz.dim.invalida</chave>
        <chave>matriz.nc.invalido</chave>
        <chave>matriz.uma.linha.esperada</chave>
        <chave>matriz.add.ao.fim.invalido</chave>
        <chave>matrizes.dims.incompativeis</chave>
        <chave>matriz.esperada</chave>
        <chave>matriz.sem.elementos</chave>
        <chave>matriz.tipo.matriz.esperado</chave>
        <chave>matriz.tipo.nao.vetor.esperado</chave>
        <chave>matriz.leitura.elemento.real.esperado</chave>
        <chave>oper.matrizes.dim.dif</chave>
        <chave>oper.mult.nao.matrizes</chave>
    </exception>
    
    <exception classeNome="VetException">
        <chave>vet.n1.maior.que.n2</chave>
        <chave>vet.inc.menor.ou.igual.a.zero</chave>
        <chave>vet.tams.diferentes</chave>
    </exception>
           
    <exception classeNome="IndiceInvalidoException">
        <chave>string.ch.indice.invalido</chave>
        <chave>string.substring.indice.invalido</chave>
        <chave>indice.fora.da.faixa</chave>
        <chave>matriz.atrib.indice.de.indice.invalido</chave>
        <chave>matriz.indice.valido.esperado</chave>
        <chave>matriz.get.el.num.indices.invalido</chave>        
    </exception>
    
    <exception classeNome="RealFormatoException">
        <chave>conversao.string.para.real.invalida</chave>
        <chave>param.tipo.string.formato.real.esperado</chave>
    </exception>
    
    <exception classeNome="BooleanFormatoException">
        <chave>conversao.real.ou.boolean.para.string.invalida</chave>
        <chave>param.tipo.string.formato.boolean.esperado</chave>
    </exception>
    
    <exception classeNome="CompareCasoException">
        <chave>compare.caso.ou.padrao.esperado</chave>
    </exception>
    
    <exception classeNome="NomeEsperadoException">        
        <chave>classe.nome.esperado</chave>
        <chave>pacote.nome.esperado</chave>
        <chave>var.nome.esperado</chave>
    </exception>
        
    <exception classeNome="OperacaoNaoEncontradaException">
        <chave>oper.nao.encontrada</chave>
    </exception>     
                
    <exception classeNome="TermoPosicInvalidaException">        
        <chave>sinal.menos.pos.invalida</chave>
        <chave>ponto.em.pos.invalida</chave>
        <chave>ch.invalido</chave>
    </exception>
        
    <exception classeNome="Plot3DException">
        <chave>plot3d.xvet.zmat.dims.incompativeis</chave>
        <chave>plot3d.yvet.zmat.dims.incompativeis</chave>
    </exception>
    
    <exception classeNome="CMDException">        
        <chave>cmd.tipo.listagem.invalido</chave>
        <chave>cmd.tipo.listagem.esperado</chave>
    </exception>
    
    <exception classeNome="ArquivoException">
        <chave>arq.nao.encontrado</chave>
        <chave>arq.erro.leitura</chave>
        <chave>arq.erro.encontrado.no.codigo</chave>
        <chave>arq.nome.esperado</chave>
        <chave>arq.classe.nativa.erro.leitura</chave>
        <chave>arq.erro.fechamento</chave>
    </exception>
    
    <exception classeNome="InstrucaoException">
        <chave>instrucao.desconhecida</chave>
        <chave>bcod.sem.instrucao</chave>
        <chave>script.exec.erro</chave>
    </exception>
    
    <exception classeNome="EstouroMemoriaException">
        <chave>mem.estouro=Estouro de mem√≥ria</chave>
    </exception>
    
    <exception classeNome="JavaException">
        <chave>java.exception</chave>
    </exception>
    
    <exception classeNome="TermoNaoExisteException">
